service: serverless-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
functions:
  app:
    handler: handler.app
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-offline
  - serverless-express
