service: serverless-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
functions:
  app:
    handler: app/handler.app
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-offline
  - serverless-express
  - serverless-webpack
custom:
  serverless-offline:
    port: 4000
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: false   # Node modules configuration for packaging
    packager: 'yarn'   # Packager that will be used to package your external modules
    packExternalModulesMaxBuffer: 200 * 1024   # Size of stdio buffers for spawned child processes
